services:
  db:
    container_name: postgres
    image: postgres
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isReady' ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres:
