/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./inertia/components/ui/accordion/Accordion.vue')['default']
    AccordionContent: typeof import('./inertia/components/ui/accordion/AccordionContent.vue')['default']
    AccordionItem: typeof import('./inertia/components/ui/accordion/AccordionItem.vue')['default']
    AccordionTrigger: typeof import('./inertia/components/ui/accordion/AccordionTrigger.vue')['default']
    Alert: typeof import('./inertia/components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./inertia/components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./inertia/components/ui/alert/AlertTitle.vue')['default']
    AppHead: typeof import('./inertia/components/AppHead.vue')['default']
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    Checkbox: typeof import('./inertia/components/ui/checkbox/Checkbox.vue')['default']
    CookieConsent: typeof import('./inertia/components/CookieConsent.vue')['default']
    DropdownMenu: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    FirstSection: typeof import('./inertia/components/about/FirstSection.vue')['default']
    Footer: typeof import('./inertia/components/Footer.vue')['default']
    FormInput: typeof import('./inertia/components/FormInput.vue')['default']
    Input: typeof import('./inertia/components/ui/input/Input.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
    Nav: typeof import('./inertia/components/home/Nav.vue')['default']
    Parallax: typeof import('./inertia/components/about/Parallax.vue')['default']
    SecondSection: typeof import('./inertia/components/about/SecondSection.vue')['default']
    Select: typeof import('./inertia/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./inertia/components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./inertia/components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./inertia/components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./inertia/components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./inertia/components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./inertia/components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./inertia/components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./inertia/components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./inertia/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./inertia/components/ui/select/SelectValue.vue')['default']
    Sonner: typeof import('./inertia/components/ui/sonner/Sonner.vue')['default']
    ToastManager: typeof import('./inertia/components/ToastManager.vue')['default']
    Vision: typeof import('./inertia/components/services/Vision.vue')['default']
  }
}
