export { default as pilarL } from './pilar-left.png'
export { default as pilarR } from './pilar-right.png'
export { default as objectL } from './object-on-floor-left.png'
export { default as objectR } from './object-on-floor-right.png'
export { default as desk } from './desk.png'
export { default as deskS } from './desk-sepia.png'
export { default as floor } from './floor.png'
