export { default as mascotteWelcome } from './mascotte-welcome.png'
export { default as mascotteWorking } from './mascotte-working.png'
export { default as mascotteDoubt } from './mascotte-doubt.png'
export { default as mascotteDoubtL } from './mascotte-doubt-l.png'
export { default as portrait } from './portrait.png'
